### PR TITLE
Django REST Framework support

### PR DESCRIPTION
**Pull request by akx**
This builds on @NovaDev94 's excellent work in PR #68.

* The DRF features were extracted from e7cbffca7bc

In addition, there are some new features I've needed in personal work using DRF and enums:

* A new `lenient` parsing mode for enums was added; it allows parsing enums case-insensitively, and by name _or_ value. This is opt-in.
* A mode that serializes integer-valued enums by their name was added. This is opt-in and is sort of the other half to the `lenient` mode.

### CODE REVIEW

**Comment by akx** [comment]
@listingmirror @bigblind Since you were active in #68 -- would this work for you guys? :)

**Comment by bigblind** [comment]
Yep, this would work for me. I have no need for the new features, but would love to see this merged.

**Comment by akx** [comment]
@listingmirror @bigblind Released in v0.9.0, https://pypi.python.org/pypi/django-enumfields/0.9.0

**Comment by jbowman1107** [comment]
A bit late to the party here, but how will filtering work with these? No matter what I do, I am not able to use an enum field as a filter field.. It always returns no results.

**Comment by NovaDev94** [comment]
@jbowman1107 It requires a PR to the `django_filters` repo. I did a hack look like this earlier and it works (though for sure it isn't elegant).   

```python
from enumfields.fields import EnumFieldMixin
from django_filters.filters import ChoiceFilter
from django_filters.filterset import BaseFilterSet


def patch_filterset(klass):
    old_filter_for_lookup = klass.filter_for_lookup

    def new_filter_for_lookup(cls, field, lookup_type):
        if isinstance(field, EnumFieldMixin):
            choices = tuple((e.value, label) for e, label in field.choices)
            return ChoiceFilter, {'choices': choices}
        return old_filter_for_lookup(field, lookup_type)

    klass.filter_for_lookup = classmethod(new_filter_for_lookup)

patch_filterset(BaseFilterSet)
```

**Comment by jbowman1107** [comment]
Thanks Nova! With this patch, does it only work on int's only, or will it work with string values? When I tried strings, I still get nothing, when I try int's I get a message like '28 isn't a valid state'. Where before, I would get this when I would type 'Nevada' e.g. 'Nevada isn't a valid state'.

**Comment by NovaDev94** [comment]
Hi @jbowman1107, this is taken from my production codebase

```python
class Status(Enum):
    PENDING = 'pending'
    PROCESSING = 'processing'
    DELIVERING = 'delivering'
    SERVING = 'serving'
    DONE = 'done'
    DECLINED = 'declined'
    CANCELED = 'canceled'
    ERROR = 'error'

class Order(models.Model):
    status = EnumField(Status, default=Status.PENDING)
```

And it works with `?status=pending`. Please note that it use the Enum value (not the label or so).

**Pull request merged**
