### PR TITLE
Add support for Python 3.7 and Django 2.1-2.2

### PR DESCRIPTION
**Pull request by johnthagen**
Supported Python versions are: https://docs.djangoproject.com/en/2.1/faq/install/#what-python-version-can-i-use-with-django

`dist: xenial` is required for Python 3.7+.

### CODE REVIEW

**Comment by johnthagen** [comment]
Build failure is unrelated to this PR, and another user has fixed it in their PR: https://github.com/hzdg/django-enumfields/pull/90/commits/3c44881bd5b49f07e364ea799c978b19dc3180e8. Ideally that should be merged into master first and this PR rebased, or this can be merged as is.

@hzdg, what would you prefer?

**Comment by johnthagen** [comment]
Ping @akx to see if this can get merged.

**Comment by akx** [comment]
@johnthagen Unfortunately I don't have merge privileges anymore.

**Comment by johnthagen** [comment]
@akx Is this project still maintained? @hzdg

**Comment by matthewwithanm** [comment]
@7aleb ping!

**Pull request closed without merging**
