### PR TITLE
Switch to GitHub Actions CI

### LINKED ISSUE #130: Migrate to new CI platform
If you navigate here: https://travis-ci.org/github/hzdg/django-enumfields

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

Screenshot 2021-10-24 073717

This project will need to migrate to either travis-ci.com or GitHub Actions/Circle CI/etc. 

Travis CI (.com) is no longer free for FOSS projects
- https://github.com/johnthagen/python-blueprint/issues/36

I would personally recommend GitHub Actions. An example of how to set up GitHub Actions with tox:

- https://github.com/johnthagen/python-blueprint/blob/master/.github/workflows/python.yml
- https://github.com/johnthagen/python-blueprint/blob/6f0e28e740005a97c780507786acc4b02a94e6c2/tox.ini#L12

### PR DESCRIPTION
**Pull request by akx**
Fixes #130

### CODE REVIEW

**Comment by akx** [comment]
You can see the CI results in my fork: https://github.com/akx/django-enumfields/pull/1

Someone from @hzdg needs to approve running GitHub Actions in this repository, so (sorry!) ping e.g. @lettertwo :)

**Comment by lettertwo** [comment]
> Someone from @hzdg needs to approve running GitHub Actions in this repository, so (sorry!) ping e.g. @lettertwo :)

Sorry, I no longer have the access or authority to do so! Maybe someone at HZ can facilitate this, or a transfer of ownership of this repository and pypi package? /cc @jesiah-hackinglife

**Comment by akx** [comment]
@lettertwo @jesiah-hackinglife Thanks for picking this up! I am actually a maintainer of [the PyPI package](https://pypi.org/project/django-enumfields/) – we established that in https://github.com/hzdg/django-enumfields/issues/96#issuecomment-574894871 but it seems I've lost collaborator bits on the GitHub repository 😅 

Also, if @hzdg doesn't have the bandwidth to maintain the repository anymore, we at @valohai would be happy to!

**Comment by akx** [comment]
Ping (sorry) the visible members of @hzdg: @gew @ryanbagwell. Could we move this forward, or can you initiate a transfer of this repo to us at @valohai? :)

**Comment by johnthagen** [comment]
@akx Do you think that we may need to fork the project to get updates in?

**Comment by akx** [comment]
@johnthagen Yeah, I did just that now. See https://github.com/akx/django-enumfields2 for the code and https://pypi.org/project/django-enumfields2 for the release. It's a drop-in replacement, so just `pip uninstall django-enumfields` and `pip install django-enumfields2`.

Closing this for that reason.

**Pull request closed without merging**
