### PR TITLE
Removed explicit context argument

### PR DESCRIPTION
**Pull request by ovidner**
Silences a deprecation warning from Django 2.0.

### CODE REVIEW

**Comment by pelme** [comment]
👍

This is what the deprecation warning looks like from our test suite:
```
/XXX/lib/python3.6/site-packages/django/db/models/sql/compiler.py:995: RemovedInDjango30Warning: Remove the context parameter from EnumField.from_db_value(). Support for it will be removed in Django 3.0.
    RemovedInDjango30Warning,
```

**Comment by pelme** [comment]
And this is the related Django ticket: https://code.djangoproject.com/ticket/28370

**Comment by harrybiddle** [comment]
Closes #87

**Comment by ryanhiebert** [comment]
Is there anything that I can do to assist the maintainers in merging this, or with similar work in the future? I'd be happy to help set up automated deployments to PyPI if that is something the maintainers would like.

This issue is annoying me pretty significantly, so I'm happy to help get this cleared up.

**Comment by maomorales** [comment]
Any plans on merging? :)

**Comment by ryanhiebert** [comment]
Depending on how you're pinning your dependencies, you might be able to use the commit that @ovidner made until this gets merged. Just pin it to that specific version. How exactly that works depends  on how you're pinning you're dependencies, but it should be relatively simple.

**Comment by riconnon** [comment]
@ryanhiebert @tim-schilling 
is there anything preventing merging this change?

**Comment by tim-schilling** [comment]
@riconnon We don't have permissions to merge it.

**Comment by matthewwithanm** [comment]
yo @lettertwo @7aleb can this be merged?

**Pull request merged**
