### PR TITLE
Do not include tests in the wheel

### PR DESCRIPTION
**Pull request by xavfernandez**
As they will endup at the top level of the virtual environment

### CODE REVIEW

**Comment by xavfernandez** [comment]
(and if you could release a new patch version and wheel without the tests, that would be very nice :+1: )

**Comment by akx** [comment]
Thanks, good catch.

I verified that wheels built with this fix in don't have that `tests/` directory (sdists still do).

**Comment by akx** [comment]
This fix is in https://pypi.python.org/pypi/django-enumfields/0.8.2 . :)

**Comment by xavfernandez** [comment]
Thanks for your quick response :+1:

**Pull request merged**
