### PR TITLE
Add DRF related section to README

### PR DESCRIPTION
**Pull request by sysradium**

### CODE REVIEW

**Comment by iuliux** [comment]
Good stuff I checked here, I was about to work this around.

@hzdg This PR can't really break anything, but is very useful.
Would be great if you could merge.

**Comment by sysradium** [comment]
Yeah, I have no idea why the CI is failing and it's not merged yet.

**Comment by johnthagen** [comment]
Should probably rebase the PR to deal with the broken Travis build. Note master seems to currently fail Django 110 until this commit is merged: https://github.com/hzdg/django-enumfields/pull/90/commits/3c44881bd5b49f07e364ea799c978b19dc3180e8

**Comment by akx** [comment]
Merged via 6c866d6. Thank you!

**Pull request closed without merging**
